version: '2'
services:
  cli-7.2:
    build: ./cli-7.2
    image: phpcli:7.2.1
    volumes:
      - ../:/procWrap/
  cli-7.3:
    build: ./cli-7.3
    image: phpcli:7.3.1
    volumes:
      - ../:/procWrap/
  cli-7.4:
    build: ./cli-7.4
    image: phpcli:7.4.1
    volumes:
      - ../:/procWrap/
  cli-8.0:
    build: ./cli-8.0
    image: phpcli:8.0.1
    volumes:
      - ../:/procWrap/
  cli-8.1:
    build: ./cli-8.1
    image: phpcli:8.1.1
    volumes:
      - ../:/procWrap/
  cli:
    image: phpcli:8.1.1
    volumes:
      - ../:/procWrap/
